---
- hosts: localhost 
  gather_facts: false
  connection: local
  vars_files:
  - non-prod-vars.yaml
        
  tasks: 
    - name: Onboard Team Namespaces
      import_role: 
        name: onboard 
      tags: 
        - create

    - name: Delete Team Namespaces
      kubernetes.core.k8s:
        host: "{{ ocp_host }}"
        api_key: "{{ auth_token }}"
        state: absent 
        definition: 
          api_version: v1
          kind: Namespace
          metadata: 
            name: '{{ app }}-{{ item.env }}'
      with_items: '{{ namespaces }}'
      tags: 
        - delete 
    
    
     
  
  






        
