- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    auth_token: "{{ lookup('env', 'auth_token') }}"
    ocp_host: "{{ lookup('env', 'OCP_HOST') }}"
  collections:
    - kubernetes.core
      openshift
  tasks:
  - name: Create namespace
    k8s:
      name: ansible-demo
      api_version: v1
      kind: Namespace
      state: present
  - name: Deploy hello-world pod
    #kubernetes.core.k8s:
    k8s:
      state: present
      apply: yes
      namespace: ansible-demo
      host: "{{ ocp_host }}"
      api_key: "{{ auth_token }}"
      validate_certs: no
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: hello-openshift
          labels:
            name: hello-openshift
        spec:
          selector:
            matchLabels:
              app: hello-openshift
          replicas: 1
          template:
            metadata:
              labels:
                app: hello-openshift
            spec:
              containers:
              - name: hello-openshift
                image: openshift/hello-openshift
                ports:
                - containerPort: 8080
                  protocol: TCP
                resources:
                  requests:
                    cpu: 300m
                    memory: 64Mi
                  limits:
                    cpu: 600m
                    memory: 128Mi
