apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "large-resource-limits" 
spec:
  limits:
    - type: "PersistentVolumeClaim"
      min: 
        storage: "5Gi"
      max:
        storage: "25Gi"
    - type: "Pod"
      max:
        cpu: "2" 
        memory: "4Gi" 
      min:
        cpu: "128m" 
        memory: "128m" 
    - type: Container
      default:
        cpu: "500m" 
        memory: "500Mi" 
      defaultRequest:
        cpu: "500m" 
        memory: "500Mi" 
      maxLimitRequestRatio:
        cpu: "4" 