- hosts: localhost
  vars_files:
    - vars/external_vars.yml
  tasks:
# - name: Try to login to OCP cluster
    #kubernetes.core.k8s_auth:
#   k8s_auth:
#     host: "{{ ocp_host }}"
#     username: $username
#     password: $password
     #api_key: "{{ auth_token }}"
#     validate_certs: no
#   register: k8s_auth_result
  - name: deploy hello-world pod
    #kubernetes.core.k8s:
    k8s:
      state: present
      apply: yes
      namespace: ansible-demo
      host: "{{ ocp_host }}"
     #api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_key: "{{ auth_token }}"
      validate_certs: no
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: hello-openshift
          labels:
            name: hello-openshift
        spec:
          selector:
            matchLabels:
              app: hello-openshift
          replicas: 1
          template:
            metadata:
              labels:
                app: hello-openshift
            spec:
              containers:
              - name: hello-openshift
                image: openshift/hello-openshift
                ports:
                - containerPort: 8080
                  protocol: TCP
                resources:
                  requests:
                    cpu: 300m
                    memory: 64Mi
                  limits:
                    cpu: 600m
                    memory: 128Mi
