apiVersion: v1
kind: ResourceQuota
metadata:
  name: large-compute-resources
spec:
  hard:
    pods: "16" 
    requests.cpu: "2" 
    requests.memory: 8Gi 
    limits.cpu: "2" 
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    requests.storage: "50Gi"