---
# tasks file for create-namespace
- name: Create Namespace 
  #kubernetes.core.k8s:
  k8s:
    state: present
    definition: 
      api_version: v1
      kind: Namespace
      metadata: 
        name: '{{ app }}-{{ item.env }}'
        labels: 
          size: '{{ item.size }}' 
  with_items: '{{ namespaces }}'

- name: Apply Limit Ranges 
  #kubernetes.core.k8s:
  k8s:
    state: present 
    src: '{{ role_path }}/files/limitranges/{{ item.size }}.yaml'
    namespace: '{{ app }}-{{ item.env }}'
  with_items: '{{ namespaces }}'

- name: Apply Resource Quotas 
  #kubernetes.core.k8s:
  k8s:
    state: present 
    src: '{{ role_path }}/files/resourcequotas/{{ item.size }}.yaml'
    namespace: '{{ app }}-{{ item.env }}'
  with_items: '{{ namespaces }}'

- name: Apply Rolebindings 
  block: 
    - name: DEV Env Rolebindings 
      #kubernetes.core.k8s:
      k8s:
        state: present 
        #template: '{{ role_path }}/files/rolebindings/dev.yaml'
        src: '{{ role_path }}/files/rolebindings/dev.yaml'
        namespace: '{{ app }}-{{ item.env }}'
      when: item.env == 'dev'
      with_items: '{{ namespaces }}'

    - name: QA/UAT/PROD Env Rolebindings 
      #kubernetes.core.k8s:
      k8s:
        state: present 
        #template: '{{ role_path }}/files/rolebindings/qa-uat-prod.yaml'
        src: '{{ role_path }}/files/rolebindings/qa-uat-prod.yaml'
        namespace: '{{ app }}-{{ item.env }}'
      when: item.env != 'dev'
      with_items: '{{ namespaces }}'
