---
# tasks file for create-namespace
- name: Create Namespace 
  kubernetes.core.k8s:
    host: "{{ ocp_host }}"
    api_key: "{{ auth_token }}"
    state: present
    definition: 
      api_version: v1
      kind: Namespace
      metadata: 
        name: '{{ app }}-{{ item.env }}'
        labels: 
          size: '{{ item.size }}' 
  with_items: '{{ namespaces }}'

- name: Apply Limit Ranges 
  kubernetes.core.k8s:
    host: "{{ ocp_host }}"
    api_key: "{{ auth_token }}"
    state: present 
    src: 'files/limitranges/{{ item.size }}.yaml'
    namespace: '{{ app }}-{{ item.env }}'
  with_items: '{{ namespaces }}'

- name: Apply Resource Quotas 
  kubernetes.core.k8s:
    host: "{{ ocp_host }}"
    api_key: "{{ auth_token }}"
    state: present 
    src: 'files/resourcequotas/{{ item.size }}.yaml'
    namespace: '{{ app }}-{{ item.env }}'
  with_items: '{{ namespaces }}'

- name: Apply Rolebindings 
  block: 
    - name: DEV Env Rolebindings 
      kubernetes.core.k8s:
        host: "{{ ocp_host }}"
        api_key: "{{ auth_token }}"
        state: present 
        template: 'files/rolebindings/dev.yaml'
        namespace: '{{ app }}-{{ item.env }}'
      when: item.env == 'dev'
      with_items: '{{ namespaces }}'

    - name: QA/UAT/PROD Env Rolebindings 
      kubernetes.core.k8s:
        host: "{{ ocp_host }}"
        api_key: "{{ auth_token }}"
        state: present 
        template: 'files/rolebindings/qa-uat-prod.yaml'
        namespace: '{{ app }}-{{ item.env }}'
      when: item.env != 'dev'
      with_items: '{{ namespaces }}'
